/**
 * Comprehensive Neomodels Data
 * Complete list of providers and models supported
 * Data structure for the neomodels integration
 */

export const NEOMODELS_PROVIDERS = {
  // Aggregators - Third-party APIs offering models from multiple providers
  '302ai': {
    id: '302ai',
    name: '302.AI',
    category: 'aggregator' as const,
    website: 'https://302.ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['NEOMODELS_302AI_API_KEY'],
    documentation: 'https://docs.302.ai',
  },
  abacusai: {
    id: 'abacusai',
    name: 'Abacus AI',
    category: 'aggregator' as const,
    website: 'https://abacusai.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['NEOMODELS_ABACUSAI_API_KEY'],
    documentation: 'https://docs.abacusai.com',
  },
  aiHubMix: {
    id: 'aiHubMix',
    name: 'AIHubMix',
    category: 'aggregator' as const,
    website: 'https://aihmix.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['NEOMODELS_AIHMIX_API_KEY'],
    documentation: 'https://docs.aihmix.com',
  },
  aliyunDashScope: {
    id: 'aliyunDashScope',
    name: 'Alibaba Dashscope',
    category: 'aggregator' as const,
    website: 'https://dashscope.aliyun.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['NEOMODELS_DASHSCOPE_API_KEY'],
    documentation: 'https://dashscope.aliyun.com',
  },

  // Direct Providers - Official APIs
  openai: {
    id: 'openai',
    name: 'OpenAI',
    category: 'direct' as const,
    website: 'https://openai.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['OPENAI_API_KEY'],
    documentation: 'https://platform.openai.com/docs',
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'direct' as const,
    website: 'https://anthropic.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['ANTHROPIC_API_KEY'],
    documentation: 'https://docs.anthropic.com',
  },
  google: {
    id: 'google',
    name: 'Google (Gemini)',
    category: 'direct' as const,
    website: 'https://ai.google.dev',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['GOOGLE_API_KEY'],
    documentation: 'https://ai.google.dev/docs',
  },
  aws: {
    id: 'aws',
    name: 'AWS Bedrock',
    category: 'direct' as const,
    website: 'https://aws.amazon.com/bedrock',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['AWS_REGION', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'],
    documentation: 'https://docs.aws.amazon.com/bedrock',
  },
  cohere: {
    id: 'cohere',
    name: 'Cohere',
    category: 'direct' as const,
    website: 'https://cohere.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['COHERE_API_KEY'],
    documentation: 'https://docs.cohere.com',
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'direct' as const,
    website: 'https://mistral.ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['MISTRAL_API_KEY'],
    documentation: 'https://docs.mistral.ai',
  },
  meta: {
    id: 'meta',
    name: 'Meta (Llama)',
    category: 'direct' as const,
    website: 'https://www.meta.com',
    enabled: true,
    configurable: false,
    documentation: 'https://www.llama.com',
  },
  xai: {
    id: 'xai',
    name: 'xAI (Grok)',
    category: 'direct' as const,
    website: 'https://x.ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['XAI_API_KEY'],
    documentation: 'https://docs.x.ai',
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    category: 'direct' as const,
    website: 'https://groq.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['GROQ_API_KEY'],
    documentation: 'https://console.groq.com',
  },
  together: {
    id: 'together',
    name: 'Together AI',
    category: 'direct' as const,
    website: 'https://together.ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['TOGETHER_API_KEY'],
    documentation: 'https://docs.together.ai',
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'direct' as const,
    website: 'https://perplexity.ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['PERPLEXITY_API_KEY'],
    documentation: 'https://docs.perplexity.ai',
  },
  huggingface: {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'direct' as const,
    website: 'https://huggingface.co',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['HUGGINGFACE_API_KEY'],
    documentation: 'https://huggingface.co/docs/hub',
  },
  replicate: {
    id: 'replicate',
    name: 'Replicate',
    category: 'direct' as const,
    website: 'https://replicate.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['REPLICATE_API_KEY'],
    documentation: 'https://replicate.com/docs',
  },
  stabilityai: {
    id: 'stabilityai',
    name: 'Stability AI',
    category: 'direct' as const,
    website: 'https://stability.ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['STABILITY_API_KEY'],
    documentation: 'https://platform.stability.ai/docs',
  },
  cerebras: {
    id: 'cerebras',
    name: 'Cerebras',
    category: 'direct' as const,
    website: 'https://cerebras.ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['CEREBRAS_API_KEY'],
    documentation: 'https://docs.cerebras.ai',
  },
  deepinfra: {
    id: 'deepinfra',
    name: 'Deep Infra',
    category: 'direct' as const,
    website: 'https://deepinfra.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['DEEPINFRA_API_KEY'],
    documentation: 'https://deepinfra.com/docs',
  },
  fireworks: {
    id: 'fireworks',
    name: 'Fireworks AI',
    category: 'direct' as const,
    website: 'https://fireworks.ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['FIREWORKS_API_KEY'],
    documentation: 'https://docs.fireworks.ai',
  },
  nvidia: {
    id: 'nvidia',
    name: 'NVIDIA',
    category: 'direct' as const,
    website: 'https://nvidia.com',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['NVIDIA_API_KEY'],
    documentation: 'https://docs.nvidia.com',
  },

  // API Gateways
  vercelai: {
    id: 'vercelai',
    name: 'Vercel AI Gateway',
    category: 'api-gateway' as const,
    website: 'https://vercel.com/ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['AI_GATEWAY_API_KEY'],
    documentation: 'https://sdk.vercel.ai',
  },
  cloudflare: {
    id: 'cloudflare',
    name: 'Cloudflare Workers AI',
    category: 'api-gateway' as const,
    website: 'https://workers.ai',
    enabled: true,
    configurable: true,
    requiredEnvVars: ['CLOUDFLARE_ACCOUNT_ID', 'CLOUDFLARE_API_TOKEN'],
    documentation: 'https://developers.cloudflare.com/workers-ai',
  },
};

export const NEOMODELS_MODEL_CATEGORIES = {
  text: 'Text Generation',
  vision: 'Vision & Image',
  audio: 'Audio & Speech',
  multimodal: 'Multimodal',
  embedding: 'Embeddings',
  function: 'Function Calling',
};

export const NEOMODELS_MODEL_TYPES = {
  large: 'Large (>70B params)',
  medium: 'Medium (7-70B)',
  small: 'Small (1-7B)',
  tiny: 'Tiny (<1B)',
};

// Provider groups for UI display
export const NEOMODELS_PROVIDER_GROUPS = {
  aggregators: {
    label: 'Aggregators',
    description: 'Multi-provider platforms',
    providers: ['302ai', 'abacusai', 'aiHubMix', 'aliyunDashScope'],
  },
  frontier: {
    label: 'Frontier Models',
    description: 'Latest cutting-edge models',
    providers: ['openai', 'anthropic', 'google', 'xai'],
  },
  opensource: {
    label: 'Open Source',
    description: 'Community and research models',
    providers: ['meta', 'mistral', 'huggingface', 'replicate'],
  },
  inference: {
    label: 'Inference Platforms',
    description: 'Fast inference services',
    providers: ['groq', 'together', 'fireworks', 'deepinfra'],
  },
  specialized: {
    label: 'Specialized',
    description: 'Domain-specific providers',
    providers: ['cohere', 'perplexity', 'stabilityai', 'cerebras', 'nvidia'],
  },
  enterprise: {
    label: 'Enterprise',
    description: 'Enterprise cloud platforms',
    providers: ['aws', 'vercelai', 'cloudflare'],
  },
};
